import { readFile, writeFile } from 'node:fs/promises';

const catalog = JSON.parse(await readFile(new URL('../node_modules/bootstrap-icons/font/bootstrap-icons.json', import.meta.url), 'utf8'));
const target = new URL('../projects/lib/src/lib/bootstrap-icons.ts', import.meta.url);
const content = '// Generated by npm run sync:icons from bootstrap-icons. Do not edit manually.\n\n'
  + `export const allIconsList = ${JSON.stringify(catalog, null, 2)};\n`;

if (process.argv.includes('--check')) {
  const current = (await readFile(target, 'utf8')).replaceAll('\r\n', '\n');
  if (current !== content) {
    console.error('Icon catalog is out of date. Run npm run sync:icons.');
    process.exitCode = 1;
  }
} else {
  await writeFile(target, content);
  console.log(`Updated ${Object.keys(catalog).length} icons.`);
}
